baseURL = "https://mattlilley.com/"
title = "Matt Lilley"

copyright = ""
pagination.pagerSize = 10
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[services]
[services.disqus]
shortname = ''
[services.googleAnalytics]
id = ''

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "about"
weight = -1
[[menu.main]]
identifier = "Science"
name = "Science"
url = "tags/science"
weight = 2
[[menu.main]]
identifier = "Technology"
name = "Technology"
url = "tags/technology"
weight = 2
[[menu.main]]
identifier = "Education"
name = "Education"
url = "tags/education"
weight = 3
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "archive"
weight = 6
[[menu.main]]
identifier = "series"
name = "Series"
url = "series"
weight = 5

[params]
title = "Matt Lilley"
author = "Matt Lilley"
description = "Science, technology, education"
images=["img/home-bg.jpg"]
keywords = "blog,science,technology,education"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/matt.jpg"
bio = "Always learning, always building."
[params.social]
email="info@mattlilley.com"
twitter = "mklilley"
facebook = "mattlilleycom"
github = "mklilley"
linkedin = "matthew-lilley"
youtube = "mklilley"
instagram="mattlilleycom"
rss = true


# See https://giscus.app/
[params.giscus]
enable = false
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
